run:
    concurrency: 4
    timeout: 1m
    issues-exit-code: 1
    tests: true
    modules-download-mode: vendor
    allow-parallel-runners: true
linters:
    disable-all: true
    enable:
        # complexity
        - gocyclo
        - gocognit
        - cyclop
        - funlen
        # bugs
        - noctx
        - errcheck
        - gosec
        - staticcheck
        # performance
        - govet
        - prealloc
        # code style + cleanup
        - deadcode
        - revive
        - varcheck
        - structcheck
        - dupl
        - ineffassign
        - unconvert
        - goconst
        - nakedret
        - misspell
        - unused
        - unparam
        - gocritic
        - depguard
        # formatters
        - gofmt
        - goimports
linters-settings:
    gocyclo:
        min-complexity: 22
    gocognit:
        min-complexity: 20
    cyclop:
        max-complexity: 22
        package-average: 0.0
        skip-tests: false
    funlen:
        lines: 130
        statements: 100
    errcheck:
        check-type-assertions: true
        check-blank: false
    govet:
        enable-all: true
        check-shadowing: true
    prealloc:
        simple: true
        range-loops: true
        for-loops: false
    revive:
        ignore-generated-header: true
        severity: warning
        rules:
            - name: line-length-limit
              arguments: [ 180 ]
            - name: function-result-limit
              arguments: [ 3 ]
            - name: argument-limit
              arguments: [ 6 ]
            - name: blank-imports
            - name: error-return
            - name: increment-decrement
            - name: deep-exit
            - name: var-declaration
            - name: package-comments
            - name: dot-imports
            - name: blank-imports
            - name: exported
            - name: unreachable-code
            - name: waitgroup-by-value
            - name: early-return
            - name: indent-error-flow
            - name: range
            - name: errorf
            - name: error-naming
            - name: error-strings
            - name: receiver-naming
            - name: increment-decrement
            - name: error-return
            - name: unexported-return
            - name: time-naming
            - name: context-keys-type
            - name: context-as-argument
            - name: defer
            - name: nested-structs
            - name: var-naming
              arguments: [
                  ["ID", "HTTP", "GUID", "UUID", "SQL", "SSH", "JSON", "API"],
                  ["URL", "DB"]
              ]
    dupl:
        threshold: 150
    goconst:
        min-len: 5
        min-occurrences: 3
        ignore-tests: false
        match-constant: true
        numbers: false
        ignore-calls: true
    misspell:
        locale: US
        ignore-words:
            - cancelled
    unused:
        go: "1.15"
    depguard:
        list-type: blacklist
        include-go-root: false
        packages: []
        packages-with-error-message: []
    gofmt:
        simplify: true

